platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
  - name: version
  - name: ci

outputs:
  - name: release-info

run:
  path: ci/ci/tasks/scripts/build-release-info.sh
